# Generated by Django 5.1.5 on 2025-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('cnic', models.CharField(max_length=15)),
                ('domicile', models.CharField(max_length=100)),
                ('student_class', models.CharField(choices=[('9th', '9th Class'), ('10th', '10th Class'), ('1st Year Medical', '1st Year Medical'), ('1st Year Non-Medical', '1st Year Non-Medical'), ('1st Year ICS', '1st Year ICS')], max_length=30)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
