# Generated by Django 5.1.5 on 2025-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='fees',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
